### ISSUE TITLE
Something wrong while running the demo code.

### ISSUE THREAD

**Issue by prikevs** [ondryaso/pi-rc522#2]
*  When I run your first demo code with no util, I gotta an error while reading cards.
*  I tried to debug in RFID.py, found that when I call the function rdr.read(block_address), In RFID.py, the write() function in read() returns an empty list.
*  Your second demo code runs well, I have no idea why this happens.

*  At last, could you please tell me can this RF522 module with your lib rewrite the uid of some cards whose uid have been declared to be able to be modified.

Thanks a lot !

**Comment by faultylee** [comment]
@prikevs the demo code is missing `select_tag()` before calling `card_auth()`. You can see the updated readme [here](https://github.com/faultylee/pi-rc522)
