### ISSUE TITLE
New release on pypi possible?

### ISSUE THREAD

**Issue by s-martin** [ondryaso/pi-rc522#68]
It looks like the last release on pypi was in 2017 (see https://pypi.org/project/pi-rc522/#history).

Would it be possible to release a new version on pypi as there were some changes and fixes in the meantime?

**Comment by wgrover** [comment]
Seconded.  One of the methods I'm using, `set_antenna_gain()`, is implemented in the version here but not the version on pypi.  Is it possible to release a new version there?  Thanks!

**Comment by s-martin** [comment]
There was a release in 2023, so my issue is fixed.
